appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: eM11ogVttVrYXIkjcd8+6IOQzy/zK3AEtGRVnRI4Tkgt4ognwdvFExpRPTP03P8Dcuy5YiKdN0fweqqr5i9ENiVS8mJXun3DREsX/+/fyuRbgMdad10BcuEv2c0L2x8uY31Z/XkefJWOlDZh3Nz/tlrs9MEqVze8x52A8+X/h8BRgJDAnwXLv+ci/4U9N7qrz+jemlGJCCWWzyMPixwT9aD6vlC957FYET9mMPqBYwWfJk7QsvFKLiFrA3InyUej7TNS3RKWiKfzRBYnrH8v93Y2baJ+dpgZOI2niY2LRe6FHZ/uRzDuX4AIlRtFCZ6mPpuAp7RhBjeRd9x+MIqoIvUw37jHhWBmhGD1wdXHrys8PHiVVsm44QI6Lcg4EtoyT7OWHP8T3/vIrkTmqOIFqwxAq359OulQroHJ/TPwgqD7ncRDw6FQImwdRBe5GkI+xplIDeUWqO7Ii7Gg47PlFYj87P1T0C4OtiE3L1888gZp4ZyYbAkLIQnFVZ267idm48IeyfehEyrGlQ94e+YodIIDWg0M4d4cTSSkp239y0ZKABhHr+e0InexSXV3i12YGodTWlKxyYYr0uBicTyFah14h+jVn3G+/JgVEIKYx07gIA0oeaNbKOCFfrbQTN7lq5YOqTVDwk4A/7jB0PmoX1mA/FZAvI30QTmpITPR7OI=}
bot:
  automerge: true
